### ISSUE TITLE
Store the state of the application in a database

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#113]
## problem
For now the application store the state directly in memory.
We store executions in different lists according to their states.

It could be good to store all this in a database that might be persistant and not limited by the size or the RAM. Also in the futur we will need to store some data like services, workflows, executions... so a persistant state will be necessary.

## solutions

For now the most "obvious" solution is to have a sqlite database like that is portable and don't need any setup from the node but we should have a look on different solutions that might be faster and maybe more efficient. Databases like redis, rockdb or graph database.

## requirements
It has to be portable and no setup for the enduser. We can of course always use docker but it could be good to keep docker only when you run service otherwise the dependency to docker shouldn't be required

**Comment by NicolasMahe** [comment]
- Geth is using LevelDB: https://github.com/google/leveldb (for go: https://github.com/syndtr/goleveldb)
Only key storage but seems very fast

- Facebook MyRocks is a MySQL fork that use RocksDB: http://myrocks.io/
Full SQL with better performance than MySQL

- Go SQLite: https://github.com/mattn/go-sqlite3
Can use query builder: https://github.com/Masterminds/squirrel or https://github.com/samonzeweb/godb

**Comment by NicolasMahe** [comment]
The real question is what is the complexity of queries we will execute?

We should make a list of queries we will run.

**Comment by NicolasMahe** [comment]
- Store service info -> super simple query: **Key store**
- Filtering service's events -> this is a bit more complex but we should do this only in memory for performance and reduce disk utilization: **memory**
- Workflow's task filtering -> complex query. A graph db could be way more efficient than a SQL: **graph db**

**Comment by antho1404** [comment]
good idea to list the different needs for the db and I will just add one thing more :
- list of executions with results -> this can be either a time serie database but not good if we want to query the results or any kind of database with query should be enough either sql nosql or graph

So far I didn't find so many things that we can use for graph db, the best one I found is maybe this one https://github.com/cayleygraph/cayley that can be use as a library and where you can connect almost any database you want even just use it in memory. Otherwise there is https://dgraph.io/ that I used already and have a nice documentation and a graphql api

**Comment by antho1404** [comment]
I just think now why not using [prisma](https://www.prisma.io) to have this connection to the database, they just release a new website, they manage the database for us and create an API in graphql that we can use in the core and also other applications can connect to. They also support few kinds of databases and they have neo4j on the roadmap. It's still an abstraction layer that can makes things a bit slow but that brings a lot of flexibility so definitely a solution to explore
