### ISSUE TITLE
Publish service

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#135]
- _Add dev public key to service yml_ really useful for now?
- Update API that required a Service, now they should only required the service id.
- Each deploy is a new version

**Comment by antho1404** [comment]
We need to make sure that every deployment will generate a new id. For that we need to update few thinks :
- The `mesg.yml` is a template with a docker image as variable
- The docker image need to be build and the hash of the final image need to be replaced in the `mesg.yml`
- the `mesg.yml` need to have the user address

With all that we are sure that a deployment will always be the unique if there is any kind of modification  either in the code or the service description.

Should we also include a deployment date to force a new version every time or no ?
If we run the `service deploy` two times with no modifications in between, what should be the behavior ? 
Publish two versions
or
Publish only one

@NicolasMahe what do you think. I prefer only one version but it's maybe a bit extreme to do that

**Comment by NicolasMahe** [comment]
Let's not implement the developer hash for now. let's keep it with the network.
