### ISSUE TITLE
Improve `mesg-core daemon start`

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#138]
It will be super nice to display a loader during the `mesg/daemon` image download.
As the image is big, the user can feel confuse by waiting without progress bar.

Maybe we can download the image before starting the service in order to have a progress.

@antho1404 what do you think?

**Comment by antho1404** [comment]
there is already a loader when the service is setting up the container, the loader stops when the service run. There is absolutely no need to add some extra complexity on the code
