### ISSUE TITLE
Locks in package db doesn't work correctly

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#163]
After some api calls and maybe cancel them at the "wrong" time, the db locks are not unlock and the `db.open` function indefinitely wait for the unlock...

I get this error quite often when using the `service test` command.

The solution is to restart the daemon.

@antho1404 have you experience this bug?

**Comment by antho1404** [comment]
yes I got this issue too sometime, the test was stuck at the deployment part, thanks for adding this issue

**Comment by NicolasMahe** [comment]
Fix in https://github.com/mesg-foundation/core/pull/164
