### ISSUE TITLE
Daemon logs return weird character

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#182]
When running the command `daemon logs`, every line start with a random character
```
)2018/06/01 08:05:28 Starting MESG daemon
12018/06/01 08:05:28 Server listens on [::]:50052
82018/06/01 08:05:28 Server listens on /mesg/server.sock
&2018/06/01 08:12:36 [PENDING] execute
)2018/06/01 08:12:36 [PROCESSING] execute
(2018/06/01 08:12:36 [COMPLETED] execute
&2018/06/01 08:14:02 [PENDING] execute
)2018/06/01 08:14:02 [PROCESSING] execute
&2018/06/01 08:14:47 [PENDING] execute
)2018/06/01 08:14:47 [PROCESSING] execute
(2018/06/01 08:14:47 [COMPLETED] execute
```

**Comment by antho1404** [comment]
this looks like a problem of index with a buffer

**Comment by antho1404** [comment]
<img width="713" alt="screen shot 2018-06-02 at 10 40 47 am" src="https://user-images.githubusercontent.com/1783126/40879209-7af8fb26-6651-11e8-97a8-bf737fe49090.png">

it looks like this is something from docker, this is a screenshot from the logs of portainer. Portainer is doing some extra work I guess to filter these extra characters.
