### ISSUE TITLE
Unsubscribe from pubsub when stream disconnect.

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#189]
## Issue

When a client stream disconnect on any listening API, the pubsub should be unsubscribe.

One concerned API: https://github.com/mesg-foundation/core/blob/dev/api/core/listen_result.go#L13

**Comment by antho1404** [comment]
@ilgooz can you confirm that we can close this issue ?

**Comment by ilgooz** [comment]
I confirm we have this now. @NicolasMahe can you also confirm!

**Comment by NicolasMahe** [comment]
👍
