### ISSUE TITLE
Should return error when service emit an invalid event or result of task

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#194]
The core should throw an error when it receives non valid event or result of task from services.
It will prevent developer to send event and result of task that are not defined in the `mesg.yml` file.

It should also check for variable types, and optional/required as defined in the `mesg.yml`

- [x] validate input data
- [x] validate event data
- [x] validate result data
- [x] add strict verification when the payload doesn't have enough data (compare to the mesg.yml)
- [ ] add strict verification when the payload have too much data (compare to the mesg.yml)
- [x] only accept correct payload `map[string]interface{}`

**Comment by antho1404** [comment]
the part to validate when the payload have too much data is moved in this issue https://github.com/mesg-foundation/core/issues/294
