### ISSUE TITLE
Improve logs in daemon

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#196]
The daemon should output way more logs.
We could have levels and categories of logs that should be configurable when starting the daemon.

**Comment by NicolasMahe** [comment]
Possible lib to use:
https://github.com/op/go-logging

**Comment by NicolasMahe** [comment]
https://github.com/uber-go/zap

**Comment by NicolasMahe** [comment]
@krhubert Could you write down how your going to implement logrus? I would like to check and have the feedback of @mesg-foundation/core before you actually start.

**Comment by krhubert** [comment]
Import logrus package in the files where logging would be required.

Core will output `>=info` level to a terminal.
  - do we need some `debug` log?
  - how to configure core to show `debug` log - via conf/cmd flag(-v --debug)?

About JSON vs Text, the default one will be text, but again:
  - do we need conf file/flag (--json-output) to switch to JSON log?

@mesg-foundation/core What do you think about logging implementation, any tips, suggestions, best practices?

**Comment by ilgooz** [comment]
JSON output could be more useful to create visual metrics depending on data points from a long running mesg-core.

**Comment by NicolasMahe** [comment]
We are using viper for config like this. It's working with both ENV and file based.
I suggest that the log level and json output could be set by a viper config.
I like as default the text output.

👍
