### ISSUE TITLE
Remove from package service the func that read a path

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#202]
Those function that read something from the disk should move to `cmd` package.
We should not read anything from the disk inside the daemon.

**Comment by antho1404** [comment]
The functions to read path like `ImportFromPath` or even the `ValidService` are never called from the core and this is the responsibility of the developer.
We could just reduce the risk by having a specific sub-package for all the import/validation

**Comment by NicolasMahe** [comment]
Already done. Closing.
