### ISSUE TITLE
Cannot start MESG Core on Digital Ocean with Docker image

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#213]
When using Digital Ocean and the built in docker image we have an error when running MESG Core.
```
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on interface eth0 (xxx.xxx.xxx.xxx and yyy.yyy.yyy.yyy)
```

This is because of the initialization of swarm where we need to precise the address that we want.

**Comment by antho1404** [comment]
Current workaround is to initialize the swarm manually and give the address that we want

```
docker swarm init --advertise-addr xxx.xxx.xxx.xxx
```

**Comment by NicolasMahe** [comment]
What about removing swarm init in the core?
We could just return an good error message with the command to execute to init the swarm node with the advertise-addr flag.

https://github.com/mesg-foundation/core/blob/b862779ad7dadd2445810d1e750bab59dc94c3cf/container/container.go#L95-L111

**Comment by NicolasMahe** [comment]
@antho1404 what do you think about:

> What about removing swarm init in the core?
> We could just return an good error message with the command to execute to init the swarm node with the advertise-addr flag.

**Comment by antho1404** [comment]
I think we can easily catch this error and return a nice error for the user and ask them to run docker swarm. So I agree to remove the docker swarm init but we still need to check if we are on a swarm (services depends on that)
