### ISSUE TITLE
Why SubmitResultReply has an executionID?

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#217]
In the Service API, `SubmitResultReply` has an `executionID` field.
But it's useless. We should remove it.

`ExecutionID` should be only in `SubmitResultRequest` and `TaskData`.

**Comment by antho1404** [comment]
What about if your service wants to handle this error and return another result in that case ? or even just do a retry, we need to make sure that they can identify the execution that we are talking about so no it might be useful, I think most of services will not add this kind of complexity and will probably not handle errors but if they want to like that they can
