### ISSUE TITLE
Command service test interactive

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#259]
The command service test is not practical and efficient to use.
To test many tasks, we have to run the test command multiple times.
We have to set the filter events when starting the command.

We should make the command test interactive with https://github.com/gizak/termui
- Execute task on demand
- Filter event on demand
- Re-build service
- Start / stop service
- Active / desactive logs

**Comment by antho1404** [comment]
close in favor of https://github.com/mesg-foundation/core/issues/288
we can still improve more the commands created in this issue
