### ISSUE TITLE
Use a specific tag for the mesg/core docker image in CLI

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#264]
Right now, we are using the latest tag when starting the Core in docker. The problem is if the user already has a core image on his computer, it may not update to the real latest.

To fix this problem, we should specify a tag in the CLI when starting the `core` in docker:
`mesg/core:v1.0.0` instead of `mesg/core:latest`.

**Comment by ilgooz** [comment]
I think versioning behavior should be like this:
* `mesg-core start` equivalent to  `mesg-core start --tag latest`
use image with latest tag
* `mesg-core start --tag v1.0.0`
use image with v1.0.0 tag 
* `mesg-core start --force --tag latest` 
use image with latest tag with a fresh registry pull

**Comment by NicolasMahe** [comment]
Interesting solution but the main problem here is to keep in sync the CLI and the Core versions.
The CLI is the binary and the Core is the docker image.

So if a user already download and start the CLI and Core, then update the CLI, with the current way to start the Core, it will start the version of the Core that already exists on the user's computer and thus not start the real 'latest' version of the Core.

You solution is interesting but we don't want to manage the complexity of managing multiple version of the CLI and Core.

**Comment by NicolasMahe** [comment]
Also in the `Dockerfile` of this project, no version are specified... Should fix it as well.

**Comment by NicolasMahe** [comment]
# To do:

- [ ] Use a specific docker image tag instead of `latest` in the default value of `config.CoreImage`.
The tag should be passed during the build. Maybe we can directly use `version.Version`?
https://github.com/mesg-foundation/core/blob/2b8569de190040fe831983fdefa0a8c0f2592d68/config/api.go#L43
- [ ] Optional: make the command "start" accept version flag and use it to start the core as proposed by @ilgooz
