### ISSUE TITLE
Investigate test with address already in use

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#268]
Sometime when running the tests we have the error 

`Address already in use, failed to allocate gateway (10.0.1.1): Address already in use`

This shouldn't happen and need to be investigated and fixed to always have reliable builds

**Comment by ilgooz** [comment]
This can be related with a bug in docker or docker client:
* https://github.com/moby/moby/issues/35204
* https://github.com/moby/moby/issues/35834

I investigated this issue for an hour yesterday but I didn't come up with a solid fix yet.  Putting a 3 second sleep above the line of [here](https://github.com/mesg-foundation/core/blob/dev/container/network.go#L56) or [here](https://github.com/mesg-foundation/core/blob/dev/container/network.go#L38) solves this problem somehow. Maybe there is something async process going on when creating a network on docker's side or there is some name conflicts in network-service relationship.

But converting to [unit tests](https://github.com/mesg-foundation/core/issues/283) should definitely solve this if we don't have a business logic mistake in our side.

**Comment by NicolasMahe** [comment]
This issue didn't occured for a long time. It should have been fixed with the fix on listening docker's event for network deletion.
