### ISSUE TITLE
Create better error when core is not running

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#269]
Now, when we execute a command that requires the core, and the core is not running, we get really not user friendly error. Eg:
```
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp :50052: connect: connection refused"
```

We should detect if the core is running and return a nice message like:
```
The Core is not running.
Please start the Core with the command: "mesg-core start"
```

**Comment by antho1404** [comment]
fixed with https://github.com/mesg-foundation/core/pull/299
