### ISSUE TITLE
Improve template of command service gen doc

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#270]
The template of the command `service gen-doc` does not include the keys `name`.

The result should be something very similar to the excellent README of this repo: https://raw.githubusercontent.com/mesg-foundation/service-ethereum-erc20/master/README.md

Related to #258 and #267.

**Comment by NicolasMahe** [comment]
Don't forget `optional` inputs!

**Comment by ilgooz** [comment]
lets also generate "Table of Contents"

**Comment by NicolasMahe** [comment]
Also, it should not replace an existing readme but just update the definitions. Maybe use a comment / tag system.
Related to https://github.com/mesg-foundation/core/issues/507
