### ISSUE TITLE
Make a websocket server to expose the APIs

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#277]
Right now the API is using gRPC with some streams and streams cannot be used in a client side directly. gRPC is planning to support that but in few months only https://github.com/grpc/grpc-web.

The idea is to have a websocket API that acts as a proxy on the gRPC API and that let users to access the gRPC api even from a client side application.

With that we could easily create a website that let you deploy your service, test it, even create directly apps based on a website only (and the core running in background)

**Comment by antho1404** [comment]
some ideas for implementation

https://github.com/tmc/grpc-websocket-proxy
https://github.com/improbable-eng/grpc-web

**Comment by ilgooz** [comment]
I watched a video earlier about [Envoy](https://www.youtube.com/watch?v=RVZX4CwKhGE). They call it a special proxy gateway in between gRPC server and [grpc-web](https://github.com/grpc/grpc-web). Video gives a general technical view about Envoy. Gotto check out.

**Comment by NicolasMahe** [comment]
Moved to https://forum.mesg.com/t/make-a-websocket-server-to-expose-the-apis/150
