### ISSUE TITLE
Allow branch download in the command service deploy

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#279]
## Problem

We cannot download a specific branch when using the command service deploy.

## Solution

Be compatible with git urls that contain branch info. Eg:

```
mesg-core service deploy https://github.com/mesg-foundation/service-ethereum-erc20#mesg-token-ropsten
```

> Make sure that other command that download service also become compatible with this feature

Related to https://github.com/mesg-foundation/service-ethereum-erc20/issues/4

**Comment by NicolasMahe** [comment]
Let's discuss more if it really useful.

**Comment by ilgooz** [comment]
@NicolasMahe I think it's useful to deploy different branches to different development or production environments.

**Comment by pts-solutions** [comment]
just a thought, since we are using go-git, should we also aim to support more protocols than just HTTP(s)? In particular ssh:// which is quite frequently used and according to the [compatibility chart](https://github.com/src-d/go-git/blob/master/COMPATIBILITY.md) it should work out of the box
