### ISSUE TITLE
Service not found when delete

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#287]
## Problem

When running the command `mesg-core service list` we have a list of service but when running the command `mesg-core service delete ID_OF_THE_SERVICE`, some services are not found in the database even they are in the list

<img width="801" alt="screen shot 2018-07-17 at 5 42 29 pm" src="https://user-images.githubusercontent.com/1783126/42812728-d483051e-89e8-11e8-8c14-f4c18c24d16b.png">

**Comment by antho1404** [comment]
This is maybe related to https://github.com/mesg-foundation/core/issues/354

**Comment by NicolasMahe** [comment]
This bug should have been fixed with the refactoring of database and service package.
Closing this issue.
