### ISSUE TITLE
Improve package config

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#290]
The package config is super messy. The variables are not prefixed with MESG and there names are not explicit.

We need to improve it and mainly separate configs that are for the CLI and for the Docker.

**Comment by NicolasMahe** [comment]
- [x] DO NOT USE viper.Get in CONSTANT
- Config key should be like: `xxxx.yyyy`
- ENV variable should be like: `MESG_XXXX_YYYY`
- YML variables in file `~/.mesg/config.yml` like:
```yml
xxxx:
  yyyy: value
```

**Comment by NicolasMahe** [comment]
The PR #302 is only about improving the utilization of viper.
We should do another PR to improve the logic of the config variable.

**Comment by NicolasMahe** [comment]
Do this issue first: https://github.com/mesg-foundation/core/issues/304

**Comment by antho1404** [comment]
fixed with https://github.com/mesg-foundation/core/pull/427
