### ISSUE TITLE
Find a tool to create issues for all the TODO

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#291]
We start to have a lot of TODOs in the code and we should have these TODOs in issues so it could be good to find a tool that automatically when there is a new TODO in the code creates an issue on Github like that we can easily keep track of all the TODOs

**Comment by askunk** [comment]
Maybe this helps your project: [`github-todos`](https://github.com/naholyr/github-todos)

Just a questions does your company still hire Go developers?

**Comment by NicolasMahe** [comment]
Hi, thanks for the tool.
We already hire two developers. We plan to hire more in a few months and use gitcoin.co to reward PR.
We accept and appreciate any contribution ;) You can find info on the [wiki](https://github.com/mesg-foundation/core/wiki) on how to dev the Core.

**Comment by antho1404** [comment]
making this automatic can be annoying, we could just add a big warning message for every new TODO on a pre commit/pull git hook and encourage developers to create issues if they have pending todos
