### ISSUE TITLE
service: create a service with log task to write log messages to std output

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#298]
This can be useful to test applications. e.g. listen for whenResult and execute a log task to see logs produced by previous service. We may want to publish this log service under mesg-foundation.

Service details
* task name: log
* inputs: serviceID (string, service id of the service that emits result events), data (object, log data)

**Comment by antho1404** [comment]
I saw that you've been working on this on this repo https://github.com/ilgooz/service-log I think its good and we should have it on the https://github.com/mesg-foundation/awesome 

I don't know if it's really useful to have this under mesg-foundation. I would either use any external service or include this directly in the core as a "special" service for example with the serviceID = "LOG" or something like that

**Comment by ilgooz** [comment]
I think we should create another github user/organization and put the all core services to there, like this one. This way github.com/mesg-foundation can stay clean. 

Btw, latest version of service-logger lives [here](https://github.com/ilgooz/go-service/tree/feature/init/examples/logger).

**Comment by ilgooz** [comment]
Special names for services looks kinda nice but it seems we lose versioning that way.

**Comment by NicolasMahe** [comment]
These "special" services should not have any version if they are included with the core. The API should never be broken. Otherwise we should use another name (Log, LogV1, etc...)

**Comment by antho1404** [comment]
@ilgooz should we close this one ? we already have a the bluelogger service I think it's enough for now or should we keep this to implement this inside mesg ?

**Comment by ilgooz** [comment]
good to close this one
