### ISSUE TITLE
aurora package not correctly working on windows

### ISSUE THREAD

**Issue by pts-solutions** [mesg-foundation/core#300]
i would say this is not something urgent to address, since it is strictly cosmetics and doesn't impact any functionality of the cli. just putting this here first so we don't forget about it.

**Comment by krhubert** [comment]
Follwoing issue https://github.com/mesg-foundation/core/issues/355 we decided, colorized output (aurora) will be dropped.

**Comment by krhubert** [comment]
We're using https://github.com/fatih/color/ now and it's working on windows (tested on win10)
