### ISSUE TITLE
Improve Docker config injected in Core's container

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#305]
### Problem

The docker socket path injected in the Core's container is a constant and only works on Linux system.
API Version, TLS certificates are also not injected in the Core's container.

### Solution

Fetch the docker config from ENV variables that Docker expose on the host machine, then pass them to the Core's container on start.

**Comment by antho1404** [comment]
let's fix this issue first https://github.com/mesg-foundation/core/issues/304 and it might be enough to close this issue

**Comment by NicolasMahe** [comment]
I think we should improve the Docker's config anyway. It's never good to have config in constant.
We should read the local Docker config.

**Comment by antho1404** [comment]
This would be useful also if we want to connect to the core through docker-machine

**Comment by NicolasMahe** [comment]
Moved to https://forum.mesg.com/t/improve-docker-config-injected-in-cores-container/153
