### ISSUE TITLE
Improve service errors - add more context

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#347]
The errors of the validation functions for the service's data are not good enough. They are not explicit enough.

https://github.com/mesg-foundation/core/blob/bd84ad1d54eadfb8aa2bd79ac0c7c68f775f9c03/service/error.go#L14-L18
- [x] Rename `Key` to `EventKey` to be more specific

https://github.com/mesg-foundation/core/blob/bd84ad1d54eadfb8aa2bd79ac0c7c68f775f9c03/service/error.go#L38-L43
- [x] Rename `Key` to `TaskKey` to be more specific

https://github.com/mesg-foundation/core/blob/bd84ad1d54eadfb8aa2bd79ac0c7c68f775f9c03/service/error.go#L53-L61
- [x] Add `TaskKey` to `OutputNotFoundError` error to give more context

https://github.com/mesg-foundation/core/blob/bd84ad1d54eadfb8aa2bd79ac0c7c68f775f9c03/service/error.go#L63-L76
- [x] Rename `Key` to `OutputKey` to be more specific
- [x] Add `TaskKey` to `InvalidOutputDataError` to give more context
- [x] `e.Key` is the outputKey, not the task key. The `errorString` has to be fixed and also include the add `TaskKey`.

**Comment by ilgooz** [comment]
related with https://github.com/mesg-foundation/core/issues/337.
