### ISSUE TITLE
fix LICENCE by adding company info

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#353]

**Comment by NicolasMahe** [comment]
I'm not even sure about the License to use. Apache? GNU?
Ethereum is using GNU

**Comment by krhubert** [comment]
@NicolasMahe @antho1404 Have you decided what condition do we want to have in LICENSE. I think LICENSE is very important if someone starts to think about using mesg in their company.

**Comment by antho1404** [comment]
On this topic, I saw most of go project have the license on every files probably because we can use just a single package and not the whole project so we might need to put an automatic task to include the license on every files (eg: https://github.com/ethereum/go-ethereum)
