### ISSUE TITLE
database/service: out of sync when mesg-core restarted

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/core#354]
Database may be out of sync when mesg-core is killed/restarted and there is no way to sync it back.

Following some cli commands may show outdated output - for example `mesg-core servcie list`

**Comment by NicolasMahe** [comment]
Maybe it's because the core doesn't quit gracefully and and the gRPC server get killed and make the db crash.

https://github.com/mesg-foundation/core/blob/d017e194432cfce501a2b41bd8ffb103eb1eaa39/core/main.go#L23-L28

**Comment by krhubert** [comment]
I can't reproduce it anymore. Closing
