### ISSUE TITLE
Track service created time and up status

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/core#359]
What do you think of that? Should we track those values and display it?
Also short description would be nice (what does the service do ...) for investigation/debugging.

**Comment by ilgooz** [comment]
yes, we can show them with list command? like docker ps/service ls

**Comment by NicolasMahe** [comment]
The service's definition has already an optional description parameter. We could display it.

The uptime is a good idea 👍  But we should take into account when the service or the core crash. Only recording the start date will not be enough.

**Comment by antho1404** [comment]
We should anyway rethink the way to start services. I would recommend adding the services in a "started service database" and when there is an insert in that then we start in docker and like that we can track the time and also not use docker api for everything but we can rely on the state. 
With that we could also restart the services if we have a crash or something like that

**Comment by ilgooz** [comment]
I'm not 100% familiar with implementation details of this but, I agree with @antho1404 to not put any state related to our business logic onto Docker API. This over complicates things.

**Comment by NicolasMahe** [comment]
Moved to https://forum.mesg.com/t/track-service-deployed-time/154
