### ISSUE TITLE
change the cli binary name from mesg-core to mesgcore or mesg

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#365]
mesg-core is hard to write. and autocomplete for mesg-core name happens in 4 steps:
* `$ m` presses to tab
* `$ mesg` auto completes to _mesg_
* `$ mesg-c` i type _-c_ and hit tab
* `$ mesg-core` autocompletes to _mesg-core_

but when we choose _mesg_ or _mesg-core_ as a binary name:
* `$ m` presses to tab
* `$ mesg` auto completes to _mesg_
done!

I give my vote for **mesg** as binary name.

**Comment by krhubert** [comment]
+1 for `mesg`

**Comment by antho1404** [comment]
I would love to use `mesg` but the problem with that is that it's an existing command already https://en.wikipedia.org/wiki/Mesg so it might create a lot of problems if we override this command

**Comment by ilgooz** [comment]
mesgtech, mesgcore, mesgfoundation, mesgc, just anything without a dash.

**Comment by NicolasMahe** [comment]
Is it still something that annoy you guys?

**Comment by antho1404** [comment]
I think this issue needs to be moved on the forum anyway but `mesg` will be hard to use anyway and for the autocomplete part we will always have it in 2 tabs as long as we start with `mesg` so personally I would not change anything.
