### ISSUE TITLE
refactor utils

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#373]
i see that we have quite a lot _utils.go_, _utils_ package inside the project. i think we should reduce them and serve under a root level utils package as possible but use different package names for each *different* util under _utils/_ e.g.:

```
util/
  gitutil/ > gitutil.Clone()
```

lets also give a second check to this article about package namings: https://blog.golang.org/package-names

related with this [comment](https://github.com/mesg-foundation/core/pull/371#discussion_r210832691).

**Comment by krhubert** [comment]
I propose struct like here:

https://github.com/krhubert/gox

We have already xpflag in our repo. Maybe add `x/` directory under repo root:
```
x/
  xgit/
  xpflag/
  x....
```

`util` can be used for things that won't fit into any extensions (or totally different purpose)...

**Comment by ilgooz** [comment]
i like the name _x_ instead using _util_ but is there any meaning of x anyway?

**Comment by krhubert** [comment]
yep x stands for eXtension and it's there to not get the same name for 2 pkgs (also importing git pkg into git pkg - or any other pkg name - can lead to ugly/error-prone code). I preffer `x` over `util` only because is shorter.

**Comment by ilgooz** [comment]
i like the x name but i also like to stay _package agnostic_ while naming x packages. in this context _xgit_ should be getting its name because it's related with Git, not for extending a feature of _github.com/src-d/go-git_. this way we can also put generic utils under _x_ package without worrying about if its name fits with a existing package.
