### ISSUE TITLE
Handle errors on the listening apis

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#374]
Right now we don't handle some errors when marshaling some data

https://github.com/mesg-foundation/core/blob/dev/api/core/listen_event.go#L36

https://github.com/mesg-foundation/core/blob/dev/api/core/listen_result.go#L36

https://github.com/mesg-foundation/core/blob/dev/api/service/listen_task.go#L29

**Comment by ilgooz** [comment]
closing this, already fixed by referenced PR.
