### ISSUE TITLE
Improve PubSub package

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#378]
We need a robust and fast pubsub system

- Search for existing PubSub package

**Comment by krhubert** [comment]
@antho1404 What features do we want to have in PubSub. I'll look for it, but written it + add benchmarks can be more useful for our case.

**Comment by NicolasMahe** [comment]
The advance feature will be to subscribe to a specific event with matching data.
We could start with a key/value equal, and then try to find solution with advance matching like, comparaison, regex, etc..

The goal is to do as little computation to get the right listeners as Core (with network) could have to filter millions of events on millions of listeners.

**Comment by NicolasMahe** [comment]
Let's not implement anything yet, just aggregate existing libraries and suggest idea 😃

**Comment by antho1404** [comment]
Also let's discuss about it on the forum here https://forum.mesg.com/t/listener-system-based-on-a-persistent-state/17
