### ISSUE TITLE
service: service.Start() can block forever

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#382]
Similar to https://github.com/mesg-foundation/core/pull/381.

If dependencies from same service listens from the same port, service.Start() will block forever because it waits for status _RUNNING_ for dependency containers. However, _N-1_ of them will never be in _RUNNING_ state because ports collides.

Also any other misconfiguration on _Service_ or _service file (mesg.yml)_ can cause the same issue.

**Comment by antho1404** [comment]
In this case one of the task created by the docker service will never trigger the task and so we will never get the error from that. We need to find a way to get the errors between the creation of the service (that is fine) and before the creation of the task

**Comment by ilgooz** [comment]
future note: add a test afterwards to _service/start_test.go_
```go
func TestX(t *testing.T) {
    service := &Service{
        Name: "TestServiceDependenciesListensFromSamePort",
        Dependencies: map[string]*Dependency{
            "test": {
                Image: "nginx",
                Ports: []string{"80"},
            },
            "test2": {
                Image: "nginx",
                Ports: []string{"80"},
            },
        },
    }
    fmt.Println(service.Start()) // currently blocks forever
}
```

**Comment by NicolasMahe** [comment]
Let's check if the error is still here

**Comment by krhubert** [comment]
The pbm stills exist

**Comment by NicolasMahe** [comment]
So,
The service that fail to start has one task stuck in "new" status.

What about adding a timeout on `container.waitForStatus` function?

Otherwise, we could add a more sophisticated system that consider a task as error if it didn't change status for let's say 1min.

**Comment by NicolasMahe** [comment]
I really think we should keep the restart always. It's a really nice feature for the service to restart if any error happen.
We have a pretty good error handling so far. But for this issue, docker have a weird behavior.

**Comment by NicolasMahe** [comment]
Actually, I have a solution:
This problem occurs only when the 2 docker services are start at the same time. If the services are start one by one, then the second return an error. Eg:
```go
package service

import (
	"fmt"
	"testing"
	"github.com/mesg-foundation/core/container"
)

func TestX(t *testing.T) {
	c, _ := container.New()
	service, _ := FromService(&Service{
		Name: "TestServiceDependenciesListensFromSamePort1",
		Dependencies: []*Dependency{
			{
				Key:   "1",
				Image: "nginx",
				Ports: []string{"80"},
			},
		},
	}, ContainerOption(c))
	service2, _ := FromService(&Service{
		Name: "TestServiceDependenciesListensFromSamePort2",
		Dependencies: []*Dependency{
			{
				Key:   "1",
				Image: "nginx",
				Ports: []string{"80"},
			},
		},
	}, ContainerOption(c))

	fmt.Println(service.Start()) // start correctly
	fmt.Println(service2.Start()) // return an error
}
```

Error returned:
```
[] Error response from daemon: rpc error: code = InvalidArgument desc = port '80' is already in use by service 'core-dc12e74f476172dd9a69948259e8e44666c0b12d-1' (wjqankzlrsggpvi28dp1hhqyj) as an ingress port
```

So the fix is to start the docker service one by one. We could also add an `order` parameter in the `mesg.yml` to specify in which order the services need to be start (in some case it will be: main service, then first dependency, etc... In so other case it could be: first dependency and then main service)

What do you think @mesg-foundation/core ?

**Comment by ilgooz** [comment]
Maybe we should make an exception for ports that are in use by handling this error in our side so we can return an error on _Start()_. Note that colliding ports may happen both in the private network of a MESG service and public ports that mapped to host machine.

**Comment by NicolasMahe** [comment]
Port collision can only happen on the ingress and host network because they share the same IP.
On any other network, each service/container has different IPs, so they can use the same port without collision.

**Comment by krhubert** [comment]
I like the idea to start service one after another. What we must do as well, is to create an issue in docker repo and wait for the fix, then switch to parallel service deploy
