### ISSUE TITLE
try to use sha256 for service ids

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#397]
docker labels has a max chars limit of 63. we set service id as a label while creating docker services. sha256 is 64 chars long.

**Comment by ilgooz** [comment]
@antho1404 suggests to shorten sha256 like github does for commit hashes.

if we get duplications while searching for services with the shorten hash, an error can be produced. but i think this is highly unlikely.

**Comment by ilgooz** [comment]
https://github.com/moby/moby/issues/36487

**Comment by NicolasMahe** [comment]
Let's use another `sha` that returns a shorter string. It's never good to truncate a hash, it make the uniques property way lesser.

**Comment by ilgooz** [comment]
we're going with the current one, sha1

**Comment by NicolasMahe** [comment]
As we use sha1 for generating hash and adding a namespace to it for readability purpose, we can close this issue for now.
