### ISSUE TITLE
Log of command dev are missing space between word

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#403]
The log of the dev command are missing some space in some output. Eg:

```
INFO[0266] Receive eventtransfer:{"blockNumber":3925030,"contractAddress":"0xD1d397a5010D9a6a98Bb275AeaAA5Aa9dd2990Ce","from":"0xCe7b4c6847cD236564C85C0fDb8496dF2900c411","to":"0x810835f96bb8ED0817C344829b851EDdE47bA3A8","transactionHash":"0xf5f26ac2077ee9ea68ba1014f4d2dbf99fbe72797afad4d06de2fa29a5182085","value":1999}
```

`eventtransfer` should have a space in between.

Code:
https://github.com/mesg-foundation/core/blob/d017e194432cfce501a2b41bd8ffb103eb1eaa39/cmd/service/dev.go#L83

Also please check for similar problem.

**Comment by NicolasMahe** [comment]
Event better, the JSON in `event.EventData` could be outputted using `logrus.WithFields`.

**Comment by ilgooz** [comment]
doesn't aurora dereference inner struct fields with reflection? is this why we're switching to log within #413? if so we should make a bug report to aurora.

**Comment by ilgooz** [comment]
okay, after reading the field names, is see that logs belongs to a blockchain transfer. my misunderstanding :)
