### ISSUE TITLE
Change dummy docker image used in test

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#408]
We are currently using the image `nginx` or `nginx:latest` as a dummy image to run some test with docker.
Today, nginx released a buggy image that could not start and thus break our tests.

To do:
- [ ] We should use our own image
- [ ] The image should be as small as possible
- [ ] The image should be build in the CI or at least be hosted in a MESG repo
- [ ] The image should be easily changed: _suggestion: add it in a viper config_

Here is some example where the nginx image is used:

https://github.com/mesg-foundation/core/blob/505fde73968a366ca6bf643eb9e85ce3603dadd0/service/start_test.go#L37

https://github.com/mesg-foundation/core/blob/505fde73968a366ca6bf643eb9e85ce3603dadd0/service/start_test.go#L54

**Comment by NicolasMahe** [comment]
@krhubert already created a very small image: https://github.com/krhubert/docker-sleep

**Comment by NicolasMahe** [comment]
@krhubert Could we build your docker-sleep image directly in the CI without any files?

**Comment by krhubert** [comment]
meged
