### ISSUE TITLE
Commands logs and execute are not working

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#426]
I know this is due to a work in progress but this is just a reminder to make sure not to forget 

https://github.com/mesg-foundation/core/blob/9531a5cb8b7ddc2b5418f516ef0dc7cad4d02f69/cmd/service/logs.go#L42-L43
https://github.com/mesg-foundation/core/blob/9531a5cb8b7ddc2b5418f516ef0dc7cad4d02f69/cmd/service/execute.go#L56-L57

**Comment by ilgooz** [comment]
can be closed after #435 and #441 is merged.
