### ISSUE TITLE
Break internal dependencies in service

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#437]
Event, Outputs etc... have a reference on the service and the only reason they have this is to have a nice error message. The service is never needed in the actual business logic, it's just user cosmetic so I would recommend to get rid of this because it's not really needed for the business logic and it can make things complicated in the future

related PR https://github.com/mesg-foundation/core/pull/417#pullrequestreview-153245567

**Comment by ilgooz** [comment]
#475 includes this
