### ISSUE TITLE
duplication of service with service list command

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#438]
_service list_ should not output same service more one.

core version: [dev](https://github.com/mesg-foundation/core/commit/b4704cff9f73380eb50be7e6a6cb3fe587f010f4)

to reproduce: run `mesg-core service deploy https://github.com/mesg-foundation/service-webhook twice`.

**Comment by antho1404** [comment]
Something observed that might be useful to debug

The ID displayed after the deploy is different than the one in the duplication in the list
