### ISSUE TITLE
Merge on dev trigger 2 circleCI workflow

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#460]
When merging a PR on the dev, it seems that 2 workflows are triggers.

You can see in the following screenshot that the last 2 workflows have the same commit id.

![image](https://user-images.githubusercontent.com/5823445/45462399-d20abe00-b731-11e8-89a7-bf120e9b838f.png)

Moreover, the first workflow has only 2 job: build_docker, test.
The second workflow (the right one) has 4 jobs: build_docker, test, release_docker_dev and release_cli_dev.

**Comment by NicolasMahe** [comment]
WIP in branch https://github.com/mesg-foundation/core/blob/fix/circleci-double-execution

**Comment by krhubert** [comment]
It's done (@NicolasMahe reopen it if I'm wrong)
