### ISSUE TITLE
pretty.ColorizeJSON doesn't output array or map properly

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#471]
When outputting value that are array or map, the `ColorizeJSON` function output the Go representation:
```
Receive result addPeers success: { "peers": "[map[address:10.0.1.226:50052 resolver_id:9906d3ebe34892b95883f86e40423fbac7ad71f1]]" }
```

**Comment by NicolasMahe** [comment]
Could use this package https://github.com/hokaccha/go-prettyjson

**Comment by krhubert** [comment]
There is no option to print json in one line. I've added (PR)[https://github.com/hokaccha/go-prettyjson/pull/5] about this

In case of no-acceptance of new api we can use this fork - https://github.com/krhubert/go-prettyjson
