### ISSUE TITLE
rm aurora in deploy status messages of api & service packages

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#487]
we can introduce a new flag something like _DONE_RED_ to distinct positive done messages from negative ones.

**Comment by NicolasMahe** [comment]
We should use the package pretty instead of aurora. Everything needed will be in the pretty package.

Replace:
- [ ] `aurora.Green("✔")` by `pretty.SuccessSign`
- [ ] `aurora.Red("⨯")` by `pretty.FailSign`

**Comment by ilgooz** [comment]
I think we should completely rm this and only use constant flags to indicate the positiveness of status messages. Because api package should not be aware of colors or symbols.
