### ISSUE TITLE
Error sign on the CLI can be improved

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#492]
The rendering of the `⨯` character is not the same on all the terminal

vscode
<img width="559" alt="screen shot 2018-09-24 at 12 17 07 pm" src="https://user-images.githubusercontent.com/1783126/45938402-cc478f00-bff3-11e8-8347-1f982abcf315.png">

iterm
<img width="546" alt="screen shot 2018-09-24 at 12 10 55 pm" src="https://user-images.githubusercontent.com/1783126/45938399-bd60dc80-bff3-11e8-87b2-992d06b7eaf2.png">

We should find a better one that works everywhere

**Comment by krhubert** [comment]
I think this one is fine, you won't be able to find the perfect one, because you have dozens of terminals for linux, win, mac etc. We should leave it as it is.
