### ISSUE TITLE
core_provider.Stop() should get running services from the Core

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#496]
The CLI access directly the function `service.ListRunning()`.
It should use the core API `ServiceList` to list the services and then stop them.
For now, `ServiceList` doesn't return the service's status. We can implement a first dummy version that try to stop ALL of them.
**Then in the future**, we can add the status to the `ServiceList` and stop only the running ones.

https://github.com/mesg-foundation/core/blob/c3e23fd91747f05750f9f18c699bb4910a082b7e/commands/provider/core_provider.go#L33-L66

**Comment by ilgooz** [comment]
should re-open after https://github.com/mesg-foundation/core/pull/499 is merges, this issue will be closed by another PR.

**Comment by antho1404** [comment]
I would actually keep that one but maybe change it a bit to say that the core itself when it stops should stop the running services. The actual solution of fetching the list of services and stop them all is good enough for now but it will change.
