### ISSUE TITLE
Documentation is not accurate for the deploy API

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#528]
https://docs.mesg.com/api/core.html#deployservice

We cannot send service definition to the API we have either URL or chunk of data based on the tar of the service folder

**Comment by antho1404** [comment]
Idem for all APIs that returns the service, we now have the status

**Comment by ilgooz** [comment]
I added some missing **basic** fields to returned _Service_ type by API. There are other missing but we need to decide which ones to keep or remove first. As I remember @NicolasMahe was talking about removing some fields from the _Service_ type in past.

**Comment by ilgooz** [comment]
solved by https://github.com/mesg-foundation/core/pull/530
