### ISSUE TITLE
Installer return error when docker is not launched

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#531]
The install script `bash <(curl -s https://mesg.com/install)` returns an error when docker is not launched.

```
2018/10/07 13:05:30 Error response from daemon: Bad response from Docker engine
```

**Comment by krhubert** [comment]
```bash

if [ -f /var/run/docker.pid ]; then
$path start
else
echo "start your docker dameon first and then run:"
echo "$ $path start"
fi
```

Also consider renaming path variable to something different because PATH is one of default variables.

I don't know how to edit install script , but posting solution here

**Comment by antho1404** [comment]
@krhubert the install script is in the `mesg.com` repository, in the `static` folder -> https://github.com/mesg-foundation/mesg.com/blob/master/static/install
