### ISSUE TITLE
https doesn't work for https://docs.mesg.tech

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#539]
<img width="1216" alt="screen shot 2018-10-16 at 21 31 53" src="https://user-images.githubusercontent.com/6023117/47038811-0dface00-d18b-11e8-8c0b-06c748b12f02.png">

**Comment by NicolasMahe** [comment]
The right url this https://docs.mesg.com

**Comment by ilgooz** [comment]
great, could you update the url here as com please? https://github.com/mesg-foundation/mesg-js
<img width="853" alt="screen shot 2018-10-17 at 09 06 05" src="https://user-images.githubusercontent.com/6023117/47065509-e6881d80-d1eb-11e8-92d2-b3c43d5e4cf1.png">

**Comment by antho1404** [comment]
good point, I also just in case added the https on the `.tech`
