### ISSUE TITLE
Possible memory leak with long running core

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#540]
I started a core for about 3 hours and the memory went from 0 to 250MB, we probably have a memory leak somewhere.

The core was running with an application that use erc20 service and a log service so basically listen to ~100 events every 10 sec and execute a task for each events.

<img width="463" alt="screen shot 2018-10-18 at 6 21 36 pm" src="https://user-images.githubusercontent.com/1783126/47151119-0a8a5280-d303-11e8-9e48-4acc459c6380.png">

**Comment by ilgooz** [comment]
could you share application service stack please so we can reproduce easier

**Comment by krhubert** [comment]
Done

**Comment by ilgooz** [comment]
This one requires a confirmation by running the same stack for a few hours to see if the problem is solved.

**Comment by antho1404** [comment]
<img width="459" alt="screen shot 2018-10-30 at 8 02 04 am" src="https://user-images.githubusercontent.com/1783126/47701458-20104e00-dc1a-11e8-90a6-1b03271dfdea.png">

Seems like everything is fine now
