### ISSUE TITLE
systemservices/_sources: problem with 'dep'

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#548]
dep init doesn't work for the pkgs under `systemservices/_sources` because it has an underscore prefix.

**Comment by krhubert** [comment]
`mv _sources to sources`?

**Comment by ilgooz** [comment]
@krhubert we had a conclusion of using an underscore for sources. Otherwise it'll look like a wrapper pkg. Maybe changing to `sources_` is a better option and we should make research to see if there is a way of bypassing this limitation with _dep_.

**Comment by ilgooz** [comment]
I'm in favor of completely getting rid of underscore from the beginning because it also limits go tools for import path resolving. For now, I changed it with dash.
