### ISSUE TITLE
log times are not right

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#550]
There is no adjustments for different timezones. Core outputs logs with a different time from mine.

My time is now: **13:14** (GMT+3 Istanbul).
```
✔ Core started
time="2018-10-23T10:14:47Z" level=info msg="deploying (2) system services..."
```

**Comment by antho1404** [comment]
The time is good :) it is just the ISO representation.
We don't want to manage timezone, that's really complicated to manage and really confusing for the users too. On your computer it's fine but what happen when you put it on a server which might not be in the same location. Kind of hard to know the timezone of the server and you have to convert the time anyway so better to always do it from UTC.

**Comment by ilgooz** [comment]
@antho1404 I'll accept this answer when there is a nice UI that parses these json log messages and shows in the proper timezone of user's.

But in case of users doesn't use such tool like that, I think we can have a flag like _--adjust-timezone_ to adjust timezone optionally for the logs. Because seeing logs with a different timezone from my computer doesn't make much sense.

**Comment by krhubert** [comment]
Timezones are really complex and difficult to manage. I'm also not in favor or manage it as every log collector has already built in an option to manage times (also every software I know of, sends ts in UTC to unify timezone across zones). 

Closing it for now.
