### ISSUE TITLE
weird behaviour on task execution with invalid output data

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#562]
to reproduce:
```go
// 1-
$ ./dev-core

// 2-
$ ./dev-cli service dev https://github.com/mesg-foundation/service-webhook

// 3-
$ ./dev-cli service execute -d url=https://mesg.tech -d data={} -d headers={} 4f7891f77a6333787075e95b6d3d73ad50b5d1e9
// outputs:
✔ Task "call" executed
Task call returned output error with data:
{
  "message": "Error: 2 UNKNOWN: json: cannot unmarshal string into Go value of type map[string]interface {}"
}
```

**3-** shouldn't output with _error_ task key. Because error message is belongs to a Go program whereas _service-webhook_ written in nodejs. I think this error caused from [here](https://github.com/mesg-foundation/core/blob/d23e60d/interface/grpc/service/submit_result.go#L13) but I don't know why it's combined with _error_ output key instead of having just a plain gRPC error.

**1-** One other weird thing related to this is _dev-core_ logs _SubmitResult_ twice as _error_ and _info_. Where I just expect one _error_ log:
```
time="2018-11-01T08:46:22Z" level=error msg="finished unary call with code Unknown" error="json: cannot unmarshal string into Go value of type map[string]interface {}" grpc.code=Unknown grpc.method=SubmitResult grpc.service=api.Service grpc.start_time="2018-11-01T08:46:22Z" grpc.time_ms=28.074 span.kind=server system=grpc
time="2018-11-01T08:46:22Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=SubmitResult grpc.service=api.Service grpc.start_time="2018-11-01T08:46:22Z" grpc.time_ms=1.148 span.kind=server system=grpc
```

**Comment by ilgooz** [comment]
This issue still not clear to me. I think we fixed why the error is happening in the first place with this PR: https://github.com/mesg-foundation/core/pull/601

But still, the other problem is I need to know that why we were getting the error in the following format:
```
Task call returned output error with data: # << indicates that task responded with "error" output key. shouldn't this be just a gRPC handler error?
# >> task is actually not responding with error output key as I see it in the code.
# >> so why we're getting it like that here?

# >> and this is the output data format of error output type which i don't expect it to be here.
# >> actually with the current implementation we should not get any kind of error after running execute command.
# >> it should stuck forever to wait a task result because when there is an unmarshalling error,
# >> task results never submitted to event bus: https://github.com/mesg-foundation/core/pull/601/files#diff-a88ed0b46cdfe75b7dd5e356a17affd5L14
{
  "message": "Error: 2 UNKNOWN: json: cannot unmarshal string into Go value of type map[string]interface {}"
}
```

**Comment by krhubert** [comment]
I think you will find it in the grpc code as 2 stands for UNKNOWN code in google.golang.org/grpc/codes/codes.go. I need time to look on it closer.

**Comment by krhubert** [comment]
I'm gonna close this, as it not the issue. Feel free to investigate grpc codebase.

**Comment by antho1404** [comment]
I understand why this error is returned to the client, it's actually the fault of the service and maybe the core too.

When the service execute the task, it uses promises
```js
axios({...})
  .then(x => result(x.data))
  .catch(e => error({ message: e.toString() }))
```

The call is valid but the data returned (`x.data`) is the actual html in that case not some json.
The data for the result success is a string and we expect an object so the core returns the error.
The `.catch` catch then this error and format it to send to the core that there is a problem on the execution.
The user then have the result from the core with the error that is supposed to be for the service.

Few things wrong here:
- the service should catch and send back the error from the core
- the core shouldn't accept 2 outputs from the same execution.

@ilgooz does that makes sense ?
@NicolasMahe @krhubert @ilgooz do you think we shouldn't allow this kind of behaviors ?

**Comment by krhubert** [comment]
@antho1404 @ilgooz was talking about the error format (`"Error: 2 UNKNOWN: ....`) as I understand it. Here you give the reason why this error occurs in the first place. 

> the service should catch and send back the error from the core

But It catches (I mean it receives the error) and it's up to servcie developer

```
✔ Service downloaded with success
✔ Service context received with success
✔ Image built with success
✔ Service deployed with ID: a7accc2b4143797e3846b815f85d3cd0df8d4082
✔ Service started
Listening for results and events from the service...
service | Example app listening on port 3000!
Receive result call error: {"message":"Error: 2 UNKNOWN: service sent invalid json data in output \"result\""}
```

> the core shouldn't accept 2 outputs from the same execution.

What do you mean?

**Comment by antho1404** [comment]
Sorry i updated, **the service shouldn't catch and send back the error from the core**

Once the service submit the result of the task, the task should be completed and shouldn't be allowed to continue its execution (because a result is submitted already).

If the task wants to emit multiple data while executing then it can emit some events but otherwise at the end of the execution the task need to submit only one output with the associated data.

This should be treated as a bug but even we add a double output error in this service, the service will still catch the first error and send it again and have another error
