### ISSUE TITLE
service: parameterValidator should support all types

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#564]
see [1](https://github.com/mesg-foundation/core/blob/d64035e78f60d3c378a61504b84a860f878978bf/systemservices/workflow/workflow.go#L20), [2](https://github.com/mesg-foundation/core/blob/d64035e78f60d3c378a61504b84a860f878978bf/systemservices/resolver/resolver.go#L18).

[_paramaterValidator_](https://github.com/mesg-foundation/core/blob/dev/service/validation.go#L57-L89) does not recognize struct types and any slice/map type except these two: 
_[]interface{}_, _map[string]interface{}_.

Please note that:

An interface that has a _[]string_ value cannot be asserted as _[]interface{}_ or:
An interface that has a _map[string]string_ value cannot be asserted as _map[string]interface{}_.
These can be only asserted to their *original* types like _[]string_ or _map[string]string_.
Also see https://play.golang.org/p/NVMb6YZh5E9

There are also no support for structs, slice or map of structs and nested structs.

In order to avoid type conversion to interface like in the examples 1 & 2 provided above or using _json.Unmarshal_ to do this with help of a pkg, we need to do reflection and more type assertions in the _validateType_ method to support a good range of types.

**Comment by antho1404** [comment]
I'm not sure I understand this issue, can you provide more informations on the description please

**Comment by ilgooz** [comment]
@antho1404 first post is updated

**Comment by ilgooz** [comment]
@mesg-foundation/core Do we agree on improving it to support more types? Please give thumbs up to this post.

**Comment by antho1404** [comment]
@ilgooz is this issue still valid ? we have new types for the data sent through grpc and we don't have the systemservices anymore. I think this one can be close
