### ISSUE TITLE
Replace leveldb with an other database

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/core#565]
As shown here https://github.com/syndtr/goleveldb/issues/226, leveldb might have some performance issues.

We can replace it with one of the following:

- https://github.com/dgraph-io/badger - LSM Tree
- https://github.com/etcd-io/bbolt - B+ Tree

I think for mesg usecase the LSM Tree will be better choice (so badger key/value db)

**Comment by NicolasMahe** [comment]
Moved to https://forum.mesg.com/t/replace-leveldb-with-an-other-database/147
