### ISSUE TITLE
Rename "command" property in mesg.yml

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#570]
The property `command` in the `mesg.yml` should be renamed to `arguments` because it is send to Docker API in the Args:

https://github.com/mesg-foundation/core/blob/3f76f8b5a5115035033adecd580a6ba648d8a121/service/start.go#L82

**Comment by ilgooz** [comment]
I think _command_ is a better name because we're actually setting what command should be run on start of service's container. _args_ word does not explain enough about the actual behavior.
