### ISSUE TITLE
service execute command hangs forever on unexpected data type

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#573]
This happens when received result data has a field with an unexpected type.
For example if a task's _success_ output has a field with _name(string)_ defined in the yml and service responses with _name(bool)_, cli command hangs forever on the following state:

```
✔ Task "findLocation" executed
⣷ Waiting for result... 
```

**Comment by antho1404** [comment]
I can reproduce, here is the full log, we have the error on the core logs and also on the service logs.
The problem is because we only listen for results and we don't manage the results with errors so we should subscribe to either the same stream but with a flag like `valid|invalid` or another stream for errors.

<img width="1671" alt="screen shot 2018-11-15 at 11 28 52 pm" src="https://user-images.githubusercontent.com/1783126/48566803-44646e00-e92e-11e8-9821-a7d5febe78d4.png">

**Comment by ilgooz** [comment]
@antho1404 could you give further details about your solution so we can get more contributive. 

My thinking about this problem is:

In first, services should be considered as **untrusted** because not all the services in network is open source. Which means a service may not strictly follow the rules described in its mesg.yml file. For example, for this case, service's tasks may not response with the expected type or even may not response at all.

So, verification of this should be handled by the Core and/or executor's side. 
* If a task results does not arrive within an estimated max time, it should be considered as gone and return an error.
* If a task results arrives but its response type or output key is not valid comparing to yml file then Core should notify tasks' executor about this misbehavior.

_For the second bullet:_
These notifications can be received by the executor within the _ListenResult()_ stream. We can add a new field named _error_ and fill it when there is a matching task execution done but with an error.

```go
message ListenResultRequest {
  message Error {
    string message = 1;
    // ...additional info to enable verbose error handling...
  }
  Error error = 5; // << this is new
  string serviceID = 1;     
  string taskFilter = 2;     
  string outputFilter = 3;    
  repeated string tagFilters = 4;
}
```

In this case _SubmitResult()_ should still return with an error to service but at the same time it should report this error to matching result listeners.

**Comment by ilgooz** [comment]
@antho1404 could you give further details about your solution as well? 

My thinking about this problem is:

In first, services should be considered as **untrusted** because not all the services in network is open source. Which means a service may not strictly follow the rules described in its mesg.yml file. For example, for this case, service's tasks may not response with the expected type or even may not response at all.

So, verification of this should be handled by the Core and/or executor's side. 
* If a task results does not arrive within an estimated max time, it should be considered as gone and return an error.
* If a task results arrives but its response type or output key is not valid comparing to yml file then Core should notify tasks' executor about this misbehavior.

_For the second bullet:_
These notifications can be received by the executor within the _ListenResult()_ stream. We can add a new field named _error_ and fill it when there is a matching task execution done but with an error.

```go
message ListenResultRequest {
  message Error {
    string message = 1;
    // ...additional info to enable verbose error handling...
  }
  Error error = 5; // << this is new
  string serviceID = 1;     
  string taskFilter = 2;     
  string outputFilter = 3;    
  repeated string tagFilters = 4;
}
```

In this case _SubmitResult()_ should still return with an error to service but at the same time it should report this error to matching result listeners.

**Comment by antho1404** [comment]
I was talking about a different stream that only send errors but the solution to have an error in the `ListenResult` makes sense. 
For the timeout, the service should set it (tasks can be more or less time consuming) but this can be done later

**Comment by krhubert** [comment]
Let's use oneof like:

```
message ListenResultRequest {
  message Error {
    string message = 1;
  }
  message Result {
    string serviceID = 1;     
    string taskFilter = 2;     
    string outputFilter = 3;    
    repeated string tagFilters = 4;
  }
  oneof response {
    Error error = 1;
    Result result = 2;
  }
}
```

Also maybe make `message Error` global for others rpc.

**Comment by NicolasMahe** [comment]
@ilgooz 👍 
Lines responsible:

https://github.com/mesg-foundation/core/blob/b862779ad7dadd2445810d1e750bab59dc94c3cf/api/submit_result.go#L26-L43

**Comment by ilgooz** [comment]
We need to put _error_ field into _ResultData_ not _ ListenResultRequest_, it was a mistake.

**Comment by krhubert** [comment]
https://github.com/mesg-foundation/core/blob/dev/api/submit_result.go#L26-L43

Publish all errors, not only one for unexpected data type

**Comment by NicolasMahe** [comment]
Let also check if we can apply the same logic to event.
