### ISSUE TITLE
Forbid to have len(alias) == len(id) to avoid service hijacking

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/core#607]

**Comment by NicolasMahe** [comment]
@krhubert can you provide more details and explanation please

**Comment by krhubert** [comment]
Also, 63 char is the maximum length of "labels"; see https://tools.ietf.org/html/rfc1035#section-2.3.4.

**Comment by NicolasMahe** [comment]
@krhubert This is done by https://github.com/mesg-foundation/core/pull/583, right?

**Comment by krhubert** [comment]
Yes
