### ISSUE TITLE
Issue on service deletion with alias

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#618]
Here is a scenario that doesn't make sense:

```
➜  core git:(dev) ./dev-cli service deploy /Users/nico/Developments/MESG/services/service-bitcoin
✔ Service context received with success
✔ Image built with success
✔ Service deployed with ID: d95a83b25b51be82c38ee793ed15614d08b5b51d
To start it, run the command:
        mesg-core service start d95a83b25b51be82c38ee793ed15614d08b5b51d
```
```
➜  core git:(dev) ./dev-cli service list
ID                                          ALIAS                                        NAME       STATUS
d95a83b25b51be82c38ee793ed15614d08b5b51d    bitcoin                                      Bitcoin    stopped
```

I change something on the bitcoin service, then deploy again.
```
➜  core git:(dev) ./dev-cli service deploy /Users/nico/Developments/MESG/services/service-bitcoin
✔ Service context received with success
✔ Image built with success
✔ Service deployed with ID: 06e0d1c14c142b58de2b1ded3bad63bd4fe02948
To start it, run the command:
        mesg-core service start 06e0d1c14c142b58de2b1ded3bad63bd4fe02948
```
```
➜  core git:(dev) ./dev-cli service list
ID                                          ALIAS                                        NAME       STATUS
d95a83b25b51be82c38ee793ed15614d08b5b51d    bitcoin                                      Bitcoin    stopped
06e0d1c14c142b58de2b1ded3bad63bd4fe02948    bitcoin                                      Bitcoin    stopped
```
```
➜  core git:(dev) ./dev-cli service delete bitcoin
✔ service "bitcoin" deleted
```
```
➜  core git:(dev) ./dev-cli service list
ID                                          ALIAS                                        NAME       STATUS
d95a83b25b51be82c38ee793ed15614d08b5b51d    bitcoin                                      Bitcoin    stopped
```
```
➜  core git:(dev) ./dev-cli service delete bitcoin
⨯ can't delete service "bitcoin": rpc error: code = Unknown desc = database: service bitcoin not found
there was a problem with deleting some services
exit status 1
```

----

Alias should be unique.
Few ideas on how to solve it:
- 1
When deploying a new service, we should generate a new alias for the service that have the same alias. The new problem is the old service (now with a different alias) cannot access its volumes (it will have new volumes).
- 2
When deploying a service where its alias already exist in the db, we should remove the old service (and of course ask user to confirm).

I think idea 2 was the first implementation of anthony with the error "same alias".

**Comment by NicolasMahe** [comment]
I suggest to go with idea 2. But with new flag in the command deploy to force the deletion of the previous service. For the command dev, it could delete the previous service by default.

**Comment by NicolasMahe** [comment]
If we go with idea 2, it doesn't make sense to call this stuff "alias".
It should be call "UUID". And the current ID rename to hash.

**Comment by NicolasMahe** [comment]
By implement idea 2:
> When deploying a service where its alias already exist in the db, we should remove the old service (and of course ask user to confirm).

Then SID / Alias can be use also for a basic versioning.
If a dev want to update previous version of its service and keep the volumes, then it should not change the SID / Alias. Only one version of the service could run at a time.
If a dev want to run the previous and the new version at the same time and also use new volume, then he needs to change the SID / Alias.
Eg:
```
sid: "bitcoin.v1"
// with a reverse domain name
sid: "com.mesg.service.bitcoin.v1"
sid: "com.mesg.service.bitcoin.v2"
```
And with the futur network, we could force the Service ID to have the public key of the developer :)
```
sid: "PUBLIC_KEY_OF_DEV.bitcoin.v2"
```

Also, we could implement in the futur a `Version` parameter, based on semantic versioning, and implement some rules (MAJOR.MINOR.PATCH):
- if Major change, the volumes change. The previous major version of the service could still run at the same time as the new version
- if minor or patch change, then the volume are the same. A previous minor or patch version of the service CANNOT run at the same time as the new version

@mesg-foundation/core what do you think?

**Comment by antho1404** [comment]
I don't understand why we should have unique alias, the goal is to have a single alias to help for the development but if now the alias need to be different for every deployment that's going back.

For me the problem here is that we have 2 versions of the same service (same alias).
The service is the same but the versions are not.
So for me there is two solutions:

- Totally overwrite the previous service (and remove the ID associated to the alias that we want to add when we deploy a new version)
- Keep all the versions and instead of having one alias for one id we would have one alias for multiple ids

I like the second version, @krhubert was talking about that [here](https://github.com/mesg-foundation/core/pull/583#issuecomment-441318338)
> It would be great if we can provide versioning along with alias.

and this was part of the initial proposal [here](https://github.com/mesg-foundation/core/issues/275#issuecomment-404051268) 
> Key: ID (as defined in the mesg.yml file)
Value: Array of services hashes deployed, the first one is the latest deployment so it's easy to get the latest version and we don't necessary care about the old ones.

I don't see how unique alias will be helpful here, it will be two different service but they are the same for the developer, it's just two different versions

**Comment by NicolasMahe** [comment]
TODO:

- [x] _database:_ make alias unique. https://github.com/mesg-foundation/core/pull/619
- [ ] _commands>deploy:_ if there is, ask to delete previous service with the same alias before deploying. otherwise fail.
- [ ] _commands>dev:_ if there is, delete previous service with the same alias

**Comment by NicolasMahe** [comment]
Fix in https://github.com/mesg-foundation/core/pull/619
