### ISSUE TITLE
sync completion of executions

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#637]
Currently it is possible that same execution can be completed multiple times because this [check](https://github.com/mesg-foundation/core/blob/28bd826/execution/execution.go#L78) at the beginning is not enough.

Multiple results submitted for the execution at the same time can pass that check when one of them cannot be saved to db **before**. We need a locking mechanism per execution basis.

**Comment by antho1404** [comment]
I think this issue is related to this PR https://github.com/mesg-foundation/core/pull/596

**Comment by ilgooz** [comment]
This issue is not related with #596. I need explain it in a different path. 

```go
	if execution.Status != InProgress {
		return StatusError{
			ExpectedStatus: InProgress,
			ActualStatus:   execution.Status,
		}
	}
```

We have the check above in the _execution.Complete()_ func. Put a hypothetical beakpoint right after this if statement. And submit two different results at the same time from service clients. In this case they will both pass this if statement and we'll have a race condition here because only one of them should pass. We need a locking mechanism per execution id in the Go level or database level to avoid this.

Clients should not pass multiple results for the same execution but we should avoid it anyway.

**Comment by NicolasMahe** [comment]
Closing in favor of https://github.com/mesg-foundation/core/issues/671
