### ISSUE TITLE
Fix build mocks for docker client

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#701]
With the removal of vendor, the mocks for docker client cannot be build like it was because the script was looking into vendor to get the interface:

```
mockery -name CommonAPIClient -dir ./vendor/github.com/docker/docker/client -output ./utils/docker/mocks
```

I see 3 solutions:
- Easy: Create a file that import the docker client interface and export it
- Complicated: Find the right version of the client in `go/pkg/dev`
- Ugly: execute `go mod vendor` for the mocks...

I recommend to go with solution 1.

File to fix:
https://github.com/mesg-foundation/core/blob/94e58541ca3d6ac4baf1f2cd8c191c2fce8548f1/scripts/build-mocks.sh

**Comment by krhubert** [comment]
```go
package main

import "github.com/docker/docker/client"

var _ = client.CommonAPIClient(nil)
```

`mockery -name client.CommonAPIClient -output ./utils/docker/mocks`

Maybe something like this works (so option 1 but without creating new type).
