### ISSUE TITLE
Transport is closing after ~10mn

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#759]
This might be related to the keep alive development.
After few minutes (~10mn) of a service inactivity I get the following error.

<img width="604" alt="screen shot 2019-01-30 at 10 24 59 pm" src="https://user-images.githubusercontent.com/1783126/51991552-e8959400-24dd-11e9-9333-750d117b58f9.png">

It seems ok when the service is emitting events.

**Comment by NicolasMahe** [comment]
No problem on my side with services that are running in background with command `service start` after 30min.

**Comment by NicolasMahe** [comment]
@antho1404 did you experience a similar issue? Did the demo experiences it again?

**Comment by antho1404** [comment]
Can still reproduce after 10mn, this is not happening on the demo but during development.

Workflow:
- git checkout dev (commit cf19a76cc9f4912f0eca37d6f32010ebf0da3ec8)
- ./dev-core (this runs the ethwallet, please ignore)
- update ethwallet with another sid (ethwallet2)
- ./dev-cli service dev systemservices/ethwallet
- set timer to 10mn
- come back after 10mn
<img width="1671" alt="screen shot 2019-02-04 at 9 49 59 pm" src="https://user-images.githubusercontent.com/1783126/52215553-da24ef00-28c6-11e9-9e52-c1bcf65bf29f.png">

**Comment by NicolasMahe** [comment]
PR https://github.com/mesg-foundation/core/pull/774 fix this issue.
