### ISSUE TITLE
ListenEvent, ListenResult doesn't return error when service is not running

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#761]
Those api doesn't return error if service deployed but not running...

**Comment by krhubert** [comment]
And it shouldn't. You can listen before service starts

also note ListenTask do not take serviceID.

Please provide more info on how this api should behave:

- when service is deployed, but not running
- when service is not deployed
- when service is running but it stop when api call is waiting for results
- when service sid will be replaced by another sid
- ???

**Comment by antho1404** [comment]
Yes they will not have any event if the service is not running but it will still be valid and when the service is started then they will have event. This is good behavior for me.

**Comment by NicolasMahe** [comment]
I experience this issue when developing an app, but yes it actually a valid behavior.
