### ISSUE TITLE
graceful shutdown 

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#803]
[original discussion](https://github.com/mesg-foundation/core/pull/790#discussion_r260682525)

## Flow
* Received `<-xsignal.WaitForInterrupt()`.
* Close listener with `listener.Close()` to stop _Accepting_ new application/service connections.
* Disable `ExecuteTask()` API by immediately returning every request with "shutting down" error. This way, already connected services cannot receive new execution requests with `ListenTask()`. (This error can be applied to incoming `ListenResult()`, `ListenEvent()` & `ListenTask()` requests for convenience.)
* Call `stopRunningServices()` to send shutdown signals to running services. So, connected services will gracefully shutdown by finishing ongoing tasks and sending `SubmitResult()`s to Core.
* Drain _pubsub_ queue by sending results for open `ListenResult()` streams. So, applications will receive their last results. Relevant [lines](https://github.com/mesg-foundation/core/blob/master/api/listen_result.go#L97-L122).
* Call `service.Close()` afterwards to close all connections for all clients.

**Comment by NicolasMahe** [comment]
@ilgooz can you move it to forum please

**Comment by ilgooz** [comment]
moved to forum https://forum.mesg.com/t/graceful-shutdown/262
