### ISSUE TITLE
Events are lost in the core 

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/core#833]
While doing performance tests I noticed some strange behaviour of emitting/listening events.

In short

```
➜  core git:(benchmark/service) ./dev-cli service execute -t genevents -d service=reciver -d key=foo -d n=3000 generator
✔ Task "genevents" executed
✔ Task genevents returned output success with data:
{"id":"1"}
```
While generates 3000 events only dozen of them reached the `reciver` service and after generating `30000` core is dead. 

If you want to check it then:

```
git fetch --all
git checkout benchmark/service

./dev-cli service deploy ./benchmark/reciver
./dev-cli service deploy ./benchmark/generator

./dev-cli service start reciver
./dev-cli service start generator

./dev-cli service logs reciver &

./dev-cli service execute -t genevents -d service=reciver -d key=foo -d n=3000 generator
```

**Comment by NicolasMahe** [comment]
First, you make a typo of `reciver`. It's `receiver` ;)

Do you have any clue why events are lost?
Is it linked with issue https://github.com/mesg-foundation/core/issues/793?

**Comment by krhubert** [comment]
> First, you make a typo on reciver. It's receiver ;)

Damn... :)

> Do you have any clue why events are lost?

Not yet, I just found it and heve no time to investigate more

> Is it linked with issue #793?

Don't think so, this locking issue is about execution and here we have events.

**Comment by antho1404** [comment]
Everything seems ok for me on the core. I added a counter on the emit event api and on the listen event when we broadcast the event and here are my results.

received 3000
sent 44847

I guess you are listening many time for the same events. Also keep in mind that you should not use listen event inside a service. This is not officially supported and will be with the service composition discussed [here](https://forum.mesg.com/t/service-composition/22) and part of few other discussion in the forum

**Comment by krhubert** [comment]
```
received 3000
sent 44847
```

41847 events not received and it's ok? If something emits ~45k events all of them should be received by the app.

> I guess you are listening many time for the same events. 

What do you mean by the same events? if events have the same data it should still be passed N times

> Also keep in mind that you should not use listen event inside a service.

Yes I know but for this case, it doesn't matter

**Comment by antho1404** [comment]
Maybe I wasn't clear enough. These statistics are the one from the core.
- 3000 call to emitEvent received (from the service task you've created with the parameter 3000)
- 44847 is the number of events broadcasted from the api `listenEvent`

These are numbers directly from the api in the interface/grpc package

**Comment by krhubert** [comment]
Ok, I've rechecked this and everything seems fine. The code listen for events in loop (instead out of it)
