### ISSUE TITLE
Marketplace error management

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#838]
The marketplace service should catch errors from ethereum, and should never return this kind of error

<img width="692" alt="Screen Shot 2019-03-24 at 11 19 55 pm" src="https://user-images.githubusercontent.com/1783126/54882336-80cf4a00-4e8b-11e9-8754-e65109ddc62c.png">

This error is when the same service is published twice

**Comment by NicolasMahe** [comment]
There is no way to get the error from a transaction receipt..
More pre-check could be added though.

**Comment by NicolasMahe** [comment]
todos from #874:
- [ ] [preparePublishServiceVersion.ts] add check on SID is domain name (see go implementation)
- [ ] [preparePublishServiceVersion.ts] check if version already exist on marketplace
