### ISSUE TITLE
Network not found when starting a service

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#88]
When starting a service we got an error `API error (500): network lzq8o5mccm0ytfo1zsystvnte not found`.

Step to reproduce:

Start a service
Stop the service
Start again the service

**Comment by krhubert** [comment]
```$ go test -timeout 60s -v -run=TestStartStopStart
=== RUN   TestStartStopStart

--- FAIL: TestStartStopStart (17.36s)
	require.go:765: 
			Error Trace:	start_test.go:170
			Error:      	Expected nil, but got: &errors.errorString{s:"Error response from daemon: network 8hhgzm83zhb00m6wert5x2tyi not found"}
			Test:       	TestStartStopStart
FAIL
exit status 1
FAIL	github.com/mesg-foundation/core/service	17.428s
````

The bug still exists. The test should be without time.Sleep

**Comment by NicolasMahe** [comment]
This bug should be fixed since we listen for network destroy event from the Docker api.
Closing this issue.
