### ISSUE TITLE
update default database path on breaking changes

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#882]
this is needed by the next release, because we're breaking it now since we don't nil check the `Configuration` in `Service` anymore. in the past versions it wasn't filled and now we always set it

**Comment by antho1404** [comment]
This could be done simply by modifying one of these lines
https://github.com/mesg-foundation/core/blob/90cf8700d6dcabb097c712721892d09b571a5bc7/config/config.go#L77-L79

**Comment by NicolasMahe** [comment]
@krhubert can you take care of this issue please?

It should be solve by adding a constant `version` to the path of the dbs. Either in config (see Anthony's post), or by adding a new config and update the dbs path in `main.go`:
https://github.com/mesg-foundation/core/blob/c60658d62f60649c773bae4203a74f6842116259/core/main.go#L35-L44

**Comment by krhubert** [comment]
Yep, sure

**Comment by NicolasMahe** [comment]
@antho1404 should the db service and the db execution have the same or different version?
I guess different. Can you confirm.

**Comment by antho1404** [comment]
yes different for each resources. We don't need to "deprecate" the database of execution if there is no impacts on it and the same with the services
