### ISSUE TITLE
Service for IoT

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#92]
https://thingspeak.com is a platform that already connect some IoT devices so it could be nice to create a service that connect to them to have access to all of their IoT devices

**Comment by antho1404** [comment]
We can also have a look on Azure IoT or lora wan or sigfox that are some "platform/networks" for IoT data

**Comment by NicolasMahe** [comment]
Migrated to https://github.com/mesg-foundation/awesome/issues/16
