### ISSUE TITLE
Cannot build ethwallet service

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#920]
Installing the core from scratch, I have the following issue.
```
INFO[0000] Deploying service "ethwallet" from "http://core-service-server/ethwallet.tar.gz"
FATA[0380] image build failed. The command '/bin/sh -c go mod download' returned a non-zero code: 1
```

this is because of 
```
go: gopkg.in/src-d/go-git-fixtures.v3@v3.3.0: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/67698a57fcf1e2e2f3930542ab0263846a1ad71c488399c086e4929ccb6a539b: exit status 128:
```

3 ways to solve that:
- use goproxy directly in the image
- pre-build this image with the `go mod download` already packed in a docker image
- just remove the package

If you have any other solution that might be less hacky that would be great.

**Comment by NicolasMahe** [comment]
That's a really problematic issue as it could happen on any user's computer...
The package `go-git-fixtures` is used by `go-git`.. We cannot just remove it.
I like and dislike prebuilding image for differents reasons.
Goproxy could be the temporary solution until we find a better one.

**Comment by antho1404** [comment]
Goproxy could be a good temporary solution, it just needs to be integrated directly in the ethwallet service and we need to make sure that we have a reliable server to serve this... also can't we use an existing goproxy managed by another company https://proxy.golang.org/
