### ISSUE TITLE
Mismatch between the marketplace and the cli when publish a service

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#923]
When we deploy a service from the CLI the link is not the same than the one on the Marketplace

CLI:
```
✔ Service published with success with sid "testservice" and marketplace hash "Cxy3D19E9hWmmNxRU7WXaV73mJ3bvTwDp6PMAYyW7LYF"
✔ See it on the marketplace: https://marketplace.mesg.com/services/testservice/Cxy3D19E9hWmmNxRU7WXaV73mJ3bvTwDp6PMAYyW7LYF
```

Marketplace:
```
https://marketplace.mesg.com/services/testservice/DMBeya65nkMmt3UCTnJ7C2KJH2SXeYTSbRx9GxSf2YXq
```

Here is the tx for this transaction https://ropsten.etherscan.io/tx/0xc2399171bd382b5a14e09be1bb566a4617feca7368ffe285d7df4a82797bb0f4

**Comment by NicolasMahe** [comment]
- The CLI is using the marketplace service version hash for the link.
- The website is using the service hash (the one output by command service deploy for example).

Which one should we use?
It makes sense to use the service hash and keep the marketplace hash as internal system only.
**BUT**, on the current marketplace, the service hash alone is not unique. The combination of sid, ipfs hash of the manifest data and the address of the sender needs to be unique.
If the website always require the sid and the service hash, then it's fine.

**Comment by NicolasMahe** [comment]
But in order to deploy a service using the marketplace URL:
```
mesg-core service deploy mesg://marketplace/service/9TpMWrifmGM99vE3YN7mbY8UEt7TdL9Y1GPoPoxojHeu
```
It's currently use the marketplace version hash (for unicity).
We could switch to sid + service hash if we want to use the same system for the website and deployment.

**Comment by NicolasMahe** [comment]
After discussion with Anthony, this is a website issue.
The website should use the `versionHash` instead of the service's hash.

**Comment by NicolasMahe** [comment]
Move to marketplace website repo https://github.com/mesg-foundation/marketplace.mesg.com/issues/15
