### ISSUE TITLE
Cannot purchase a service

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#935]
I cannot purchase a service that doesn't belong to me. The [service exists](https://marketplace.mesg.com/services/marketplace#offers), the offer also exists. 
The address has [sufficient funds](https://ropsten.etherscan.io/token/0x5861b3dc52339d4f976b7fa5d80db6cd6f477f1b#balances)
```
➜  core git:(dev) ✗ mesg-core marketplace purchase marketplace
? Enter the account to use 0xfde8b69e8eee1c116bc678602a752c909189f955
? Enter passphrase *
? Enter the offer index to purchase 0
? Are you sure to purchase service "marketplace" for 1 MESG Tokens and for a duration of 36000 seconds? Yes
Returned error: gas required exceeds allowance or always failing transaction
```

**Comment by NicolasMahe** [comment]
I find the source of the problem: it's the function to estimate the gas needed.
As your account didn't allow the smart contract of the marketplace to spend token on its behalf, the transaction to buy will always failed...

**Comment by antho1404** [comment]
let's force the maximum number of gas that these transactions can consume.
We need to test the maximum amount of gas the contract will need for the allowance and the purchase and then we can double it to make sure that we will always have enough.

nice catch
